### ISSUE TITLE
Can you provide the initialization pre training weights used for training YOLOX-Swin？

### ISSUE THREAD

**Issue by multi-type** [YuHengsss/YOLOV#100]
Can you provide the initialization pre training weights used for training YOLOX (YOLOX SwinTiny and YOLOX SwinBase)? I don't have this weight, so I can't get your results by training YOLOX SwinTiny from scratch according to the configuration of \exps\swin_base\swin_tiny_vid.py.Thanks!

**Comment by multi-type** [comment]
How did you obtain YOLOX-Swin Pretain Models on ImageNet VID? Please teach me.

**Comment by YuHengsss** [comment]
The COCO pretrained weights for swin-tiny backbone could be found in https://huggingface.co/YuhengSSS/YOLOV/blob/main/swin_tiny_coco_pretrained.pth. The swin-based pretrained backbone is too large to upload for now, I will get back to you when it's finished.

**Comment by YuHengsss** [comment]
Hello，the swin-based weights of COCO pretraining is available at https://huggingface.co/YuhengSSS/YOLOV/blob/main/yoloxx_swin_base384.pth .
