### ISSUE TITLE
Annotation format issues while training YOLOV++ 

### ISSUE THREAD

**Issue by sharanyap21** [YuHengsss/YOLOV#106]
Hello! I am trying to train the YOLOV++ model using a custom dataset. I am stuck on how the annotation format should look like. Here are some of the steps I have taken and more information about my progress:

1. I have already trained the base detector using COCO formatted json files and obtained the weights 
2. I created new json files for my custom video dataset and converted them to OVIS using the `convert_ovis_coco()` from the `ovis.py` file
3. I created my `train_seq.npy` and `val_seq.npy` files
4. I am using the `v++_SwinTiny_decoupleReg.py` exp file and added the following lines: 
`self.data_dir = "/mnt/c/Users/p009325H/Documents/xod-data-COLOR-video/images"  
        self.train_ann = "ovis_train.json"  
        self.val_ann = "ovis_validation.json"`
I also added the `get_data_loader()` code as well to the very end of the file
5. I then run the training using the following command: `python tools/vid_train.py -f exps/yolov++/v++_SwinTiny_decoupleReg.py -c YOLOX_outputs/swin_tiny_vid/best_ckpt.pth --fp16 -b 2`

After running, epoch1 starts and after the iterations finish, it crashes with the following error:

xml.parsers.expat.ExpatError: Caught ExpatError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sharanyap21/miniconda3/envs/yolov/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sharanyap21/miniconda3/envs/yolov/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sharanyap21/miniconda3/envs/yolov/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sharanyap21/YOLOV/yolox/data/datasets/vid.py", line 246, in __getitem__
    img, target, img_info, path = self.pull_item(path)
  File "/home/sharanyap21/YOLOV/yolox/data/datasets/vid.py", line 231, in pull_item
    annos = self.get_annotation(path, self.img_size)[0]
  File "/home/sharanyap21/YOLOV/yolox/data/datasets/vid.py", line 182, in get_annotation
    file = minidom.parse(xmls)
  File "/home/sharanyap21/miniconda3/envs/yolov/lib/python3.7/xml/dom/minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "/home/sharanyap21/miniconda3/envs/yolov/lib/python3.7/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/home/sharanyap21/miniconda3/envs/yolov/lib/python3.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

I assume it crashes in `get_annotation()` because I don't have the xml files that they are trying to use. Is there code that you provide to generate these xml files or do we need to manually generate them? Is there some other reason for this crash? Thank you for your help!

**Comment by YuHengsss** [comment]
Hello, I apologize for the oversight. The code required to get the evaluation loader was inadvertently omitted. Please add the [get_eval_loader](https://github.com/YuHengsss/YOLOV/blob/03e98152b9a6f04d538d6c6a3e5af4d840ad2d46/exps/customed_example/v%2B%2B_SwinTiny_example.py#L208) to the end of the experimet file.

I have also updated the README with the procedure for training on a custom dataset; please review it. If you encounter any further issues, do not hesitate to contact me for assistance.

Again, I apologize for any inconvenience caused.

**Comment by YuHengsss** [comment]
update: a minimal change in https://github.com/YuHengsss/YOLOV/blob/5f069b29e201c4e099c7c3827cc6c63823ce3141/exps/customed_example/v%2B%2B_SwinTiny_example.py#L221
