### ISSUE TITLE
Frame sampling method

### ISSUE THREAD

**Issue by Elstuhn** [YuHengsss/YOLOV#113]
Hey, thank you so much for your work! I think it's very good and I seriously enjoyed reading the paper so I want to do some experimentations with it and try to experiment with ways to improve or modify it.

I have read about the sampling method in the paper, that you sample globally (by default 16 frames for training) and I wish to change it such that it only samples f frames from behind the key/target frame with a stride of 2, may I know where the sampling logic/code is? 

Is the current sampling method the TrainSampler or VIDBatchSampler in yolox/data/datasets/vid.py?

**Comment by YuHengsss** [comment]
Yep, please custome this func and pass kwargs to control the sampling method:
https://github.com/YuHengsss/YOLOV/blob/5f069b29e201c4e099c7c3827cc6c63823ce3141/yolox/data/datasets/vid.py#L73

**Comment by Elstuhn** [comment]
Hey, thanks for your quick reply. I've just looked into it, it seems that function passes out a list of lists that has the same length as training iterations and each list contains randomized global frames and the intervals depend on whether the mode is random or uniform.

My goal is to get the last few frames with n intervals in between with respect to key/target frame. An example of a list inside the list given by `photo_to_sequence` is `['video1_006306.jpg', 'video1_006315.jpg', 'video1_006324.jpg', 'video1_006333.jpg', 'video1_006342.jpg', 'video1_006351.jpg', 'video1_006360.jpg', 'video1_006369.jpg', 'video1_006378.jpg', 'video1_006387.jpg', 'video1_006396.jpg', 'video1_006405.jpg', 'video1_006414.jpg', 'video1_006423.jpg', 'video1_006432.jpg', 'video1_006441.jpg']` and my question is are these 16 elements all for reference frames or is the last element the key/target frame? 

If all elements are used for reference frames, is it possible to get information of the key/target frame in the `photo_to_sequence` function so that I can get t-16 to t frames where t-th frame is the key/target frame? (basically get past 16 frames from the key/target frame)

**Comment by Elstuhn** [comment]
![image](https://github.com/user-attachments/assets/12f9b4f8-1166-4020-b307-75d95864f0c6)
![image](https://github.com/user-attachments/assets/15a63e11-89d7-4c5d-939c-030ae3d97350)

Btw, I got these twp visualisation for the attention scores on the cls score and cls score masked, just curious, how might you interpret these? I'm a bit confused,  please advise 😄

**Comment by Elstuhn** [comment]
Also regarding the MSA_yolov_visual, how do we use it to generate the visuals? I notice I cannot just replace MSA_yolov with it since the inputs for forward method is different

**Comment by Elstuhn** [comment]
```
def visual_sim(attn,imgs,simN,predictions,cos_sim):
    sort_res = torch.sort(attn,descending=True)
    #cos_sim_res = torch.sort(cos_sim,descending=True)
    img = imgs[0,:,:,:].permute(1,2,0)
    support_idx = sort_res.indices[:simN, :]
    for bidx in range(int(5)):
        box = predictions[0][bidx,:4]
        visual_pred(img,box,title='key proposal'+str(bidx))
        for sidx in range(6):
            frame_idx = support_idx[bidx,sidx]
            fth = int(frame_idx/simN)
            bth = int(frame_idx%simN)
            simg = imgs[fth,:,:,:].permute(1,2,0)
            box = predictions[fth][bth,:4]
            visual_pred(simg,box,'key-'+str(bidx)+'-support'\
                        +str(sidx)+"-"+str(float(sort_res.values[bidx,sidx]))[:4]\
                        + '-'+str(float(cos_sim[bidx,frame_idx]))[:4])
        if bidx>=5:
            break
     ```
     According to the visual_sim function it shows that the key/target frame is the first element of the images while the other images in the list are all support frames, is this correct? 
     
     And I have one other question, where is the code that you used to produce the reference and keyframe images from the paper? I found the MSA_yolov_visual function and subsequent functions but there are no files that uses it and we cannot simply swap out MSA_yolov for MSA_yolov_visual as well

**Comment by YuHengsss** [comment]
Hello, the training and inference actually could be implemented in batch, which meaning when you take one of the frame as the key frame, the others will act as the reference frames. In this case, every frame is the key frame while they act as the reference frame for others.

**Comment by YuHengsss** [comment]
> these 16 elements in my case all for reference frames or is the last element the key/target frame?
> (I see that during training, the inputs are of (gframe, 3, h, w) so I assumed that the key/target frame should be part of the 16 elements please let me know if I'm right or wrong)

The "l" frame denotes for the local frames, and in current sampling func, they just sampled like uniform with a stride parameter. However, in the VID dataset, the local frame sampling strategy is not work as well as the global one.

**Comment by Elstuhn** [comment]
> Hello, the training and inference actually could be implemented in batch, which meaning when you take one of the frame as the key frame, the others will act as the reference frames. In this case, every frame is the key frame while they act as the reference frame for others.

Oh I see, 请问 code 里面的这个 logic 是在哪里？

**Comment by Elstuhn** [comment]
> The "l" frame denotes for the local frames, and in current sampling func, they just sampled like uniform with a stride parameter. However, in the VID dataset, the local frame sampling strategy is not work as well as the global one.

Thanks for this reply, I understand now

**Comment by YuHengsss** [comment]
> > Hello, the training and inference actually could be implemented in batch, which meaning when you take one of the frame as the key frame, the others will act as the reference frames. In this case, every frame is the key frame while they act as the reference frame for others.
> 
> Oh I see, 请问 code 里面的这个 logic 是在哪里？

Due to there are not limit (such as mask or only query from key freme while key and value from the references) to the reference proposal in the attention, each proposal could receive support from all other proposals in the same batch.  So, the design is inherently "all key frames".

Btw, thank you very much for replying recent issues in this repo !

**Comment by Elstuhn** [comment]
> Due to there are not limit (such as mask or only query from key freme while key and value from the references) to the reference proposal in the attention, each proposal could receive support from all other proposals in the same batch. So, the design is inherently "all key frames".
> 
> Btw, thank you very much for replying recent issues in this repo !

Ohhhh okay I see what you mean. 没问题兄弟，我正在帮 research organization 写一个 paper 刚好看到其他的 issue 还有你看起来也很忙所以就帮帮一下。
