### ISSUE TITLE
Train Configuration File Correspondence 

### ISSUE THREAD

**Issue by AngleBeats147753** [YuHengsss/YOLOV#114]
Thanks to the excellent work of Yolov and Yolov++. However, I'm currently having some confusion regarding the code.

1. I want to train the Yolov++ model. I guess I should use the configurations in the `exps/yolov++` directory to train it. So, is the correspondence between the models and the configuration files as follows?
```
Yolov++ s : v++_base_decoupleReg.py
Yolov++ l : v++_large_decoupleReg.py
Yolov++ SwinTiny : v++_SwinTiny_decoupleReg.py
Yolov++ SwinBase : v++_SwinBaseX_decoupleReg.py
Yolov++ FocalLarge : v++_FocalLarge_decoupleReg.py
```
2. Moreover, what are the differences between `v++_base.py`,` v++_base_decoupleReg.py` and `v++_base_decoupleReg_2x.py`?
3. And is the correspondence between the base detectors for training them and the configuration files as follows?
```
Yolov++ s : exps/default/yolox_s.py
Yolov++ l : exps/default/yolox_l.py
```
4. Also, where are the configuration files for training the base detectors of `Yolov++ SwinTiny`, `Yolov++ SwinBase` and `Yolov++ FocalLarge`?
5. I don't understand the meanings of the files in the `exps/swin_base` directory at all. Could you please explain them?

**Comment by Elstuhn** [comment]
For number 4 and 5, the configuration files for training the base detectors of `Yolov++ SwinTiny`, `Yolov++ SwinBase` and `Yolov++ FocalLarge` should be in `/exps/swin_base/swin_tiny_base.py`, `/exps/swin_base/yoloxx_swin_base384_vid.py`  and `/exps/swin_base/focal_large_base_vid.py` respectively, at least those were what I used to train base detectors of YoloV++

**Comment by YuHengsss** [comment]
For the first and third question, you are right. For the second question, their differences lie in the training schedule.
