### ISSUE TITLE
the mean Average Precision (mAP) is always zero.

### ISSUE THREAD

**Issue by AngleBeats147753** [YuHengsss/YOLOV#115]
When training based on the dataset in the ovis_coco format, the mean Average Precision (mAP) is always zero.

```
Average forward time: 14.41 ms, Average NMS time: 0.00 ms, Average inference time: 14.41 ms
per class AP:
| class         | AP    | class   | AP    | class   | AP    |
|:--------------|:------|:--------|:------|:--------|:------|
| person        | 0.000 | money   | 0.000 | book    | 0.006 |
| printer paper | 0.000 | phone   | 0.000 | card    | nan   |
per class AR:
| class         | AR    | class   | AR    | class   | AR    |
|:--------------|:------|:--------|:------|:--------|:------|
| person        | 0.000 | money   | 0.000 | book    | 1.864 |
| printer paper | 0.000 | phone   | 0.106 | card    | nan   |
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.005
```

this is my yolov++ train_log: [train_log.txt](https://github.com/user-attachments/files/17866624/train_log.txt) 
this is my base detector train_log: [train_log.txt](https://github.com/user-attachments/files/17866637/train_log.txt)
this is my annotation file: [ovis_val.json](https://github.com/user-attachments/files/17866649/ovis_val.json)

This is the same as issue [#107](https://github.com/YuHengsss/YOLOV/issues/107), I will try VID dataset format according to ILSVRC too. I hope my annotation file and train log file can help optimize the training that uses the ovis_coco format.

**Comment by YuHengsss** [comment]
You may check this [issue](https://github.com/YuHengsss/YOLOV/issues/99) for help. If there are any mistakes in the guideline of training on customed dataset, please let me know so I can update them accordingly.

**Comment by YuHengsss** [comment]
You may  compare our released logs in this [google drive](https://drive.google.com/file/d/1RmY0LW1sUil6WilvNq2hW1a4obw27531/view) to estimate the version that work normaly.
