### ISSUE TITLE
Which exp has to be used with which model weight ? 

### ISSUE THREAD

**Issue by gboeer** [YuHengsss/YOLOV#123]
In the current documentation, it is very unclear which exp file has to be used with which pretrained model weight, e.g. when trying to run a demo application.

In the current quick start section it is written, that to run the demo, one has to:

    python tools/vid_demo.py -f [path to your yolov exp files] -c [path to your yolov weights] --path /path/to/your/video --conf 0.25 --nms 0.5 --tsize 576 --save_result  
 
For example, one can download the model weights for "YOLOV++ s" with the provided link.
However, when trying to figure out which exp file should be used, one is faced with those options in the `YOLOV/exps/yolov++` folder:

- v++_base_decoupleReg_2x.py  
- v++_base_decoupleReg.py
- v++_base.py
- v++_FocalLarge_decoupleReg.py
- v++_large_decoupleReg.py
- v++_SwinBaseX_decoupleReg.py
- v++_SwinTiny_decoupleReg.py

**Comment by Elstuhn** [comment]
Hello, this issue has been addressed in issue #114

**Comment by gboeer** [comment]
Oh, you're right, didn't see that. 
A real solution would be to at least document the correspondence somewhere in the readme.
