### ISSUE TITLE
Pre-training with DET and VID dataset 

### ISSUE THREAD

**Issue by mukundkhanna123** [YuHengsss/YOLOV#13]
Hey, I had a question about what training methodology was used to pre-train the yolox baseline models. I added the images from DET dataset with similar classes as the VID dataset and trained yolox-s model but I was not able to replicate your results. So could you elaborate on how you pretrained the yolox model?

**Comment by YuHengsss** [comment]
> Hey, I had a question about what training methodology was used to pre-train the yolox baseline models. I added the images from DET dataset with similar classes as the VID dataset and trained yolox-s model but I was not able to replicate your results. So could you elaborate on how you pretrained the yolox model?

Thanks for your attention. May I ask how many images you sampled from the VID dataset? We release our training annotation link for the baseline model in the README.MD file which contains 1/10 VID images and all DET images with the same classes. You can try this one and we are eager for your response

**Comment by YuHengsss** [comment]
Besides, do you use the coco pretrained model for finetuning ?

**Comment by YuHengsss** [comment]
> sampled all the images from VID dat

Please follow our instructions and try it again.

**Comment by mukundkhanna123** [comment]
My bad, I used 1/10 from VID dataset and all images from DET dataset, sorry that was a typo

**Comment by YuHengsss** [comment]
> My bad, I used 1/10 from VID dataset and all images from DET dataset, sorry that was a typo

Could you please use our annotations and try it again and keep all of other settings the same as this repo. Hopefully, we can find out the reason.
