### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by Michelvl92** [YuHengsss/YOLOV#14]
Hi, it is unclear how I can format my custom dataset to your expected format, Can possibly provide information on how I can convert my dataset, and what are you expected format? For E.g. it is unclear to me what the context is of the [video sequences](https://drive.google.com/file/d/1vJs8rLl_2oZOWCMJtk3a9ZJmdNn8cu-G/view?usp=sharing).

**Comment by YuHengsss** [comment]
> Hi, it is unclear how I can format my custom dataset to your expected format, Can possibly provide information on how I can convert my dataset, and what are you expected format? For E.g. it is unclear to me what the context is of the [video sequences](https://drive.google.com/file/d/1vJs8rLl_2oZOWCMJtk3a9ZJmdNn8cu-G/view?usp=sharing).

Hello, thanks for your attention. I'm sorry for my unclear description. The video sequences contain all of the file names from the VID dataset in list format, you can try to load it with the pickle package.  The whole structure like : [VID1,VID2,...,VIDn], while in VID1 the structure is [frame1_path, ... , framen_path].

**Comment by AlfieXiong** [comment]
> > Hi, it is unclear how I can format my custom dataset to your expected format, Can possibly provide information on how I can convert my dataset, and what are you expected format? For E.g. it is unclear to me what the context is of the [video sequences](https://drive.google.com/file/d/1vJs8rLl_2oZOWCMJtk3a9ZJmdNn8cu-G/view?usp=sharing).
> 
> Hello, thanks for your attention. I'm sorry for my unclear description. The video sequences contain all of the file names from the VID dataset in list format, you can try to load it with the pickle package. The whole structure like : [VID1,VID2,...,VIDn], while in VID1 the structure is [frame1_path, ... , framen_path].

Excuse me,if I have prepared the annotation and the file of train_sequences,how can I change the setting of exp files to add the information of video sequences for training VID models?
