### ISSUE TITLE
train model from scratch not checkpoint

### ISSUE THREAD

**Issue by AlfieXiong** [YuHengsss/YOLOV#15]

**Comment by AlfieXiong** [comment]
Dear author,I would like to train model from scratch not checkpoint;but I can not train my model if i don't set the checkpoint "-c weights/yoloxs_vid.pth".
error info:"FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by YuHengsss** [comment]
> Dear author,I would like to train model from scratch not checkpoint;but I can not train my model if i don't set the checkpoint "-c weights/yoloxs_vid.pth". error info:"FileNotFoundError: [Errno 2] No such file or directory: '' I'll appreciate for you help

I'm sorry for that. We don't test training the video object detector from scratch. I'm afraid you have to change the code and try it by yourself. Looking forward to your good news!

**Comment by Yipzcc** [comment]
> Dear author,I would like to train model from scratch not checkpoint;but I can not train my model if i don't set the checkpoint "-c weights/yoloxs_vid.pth". error info:"FileNotFoundError: [Errno 2] No such file or directory: '' I'll appreciate for you help

please change the
`    parser.add_argument("-c", "--ckpt", default='', type=str, help="checkpoint file")
`
to
`    parser.add_argument("-c", "--ckpt", default=None, type=str, help="checkpoint file")
`
and try again
