### ISSUE TITLE
About the model's random select frame input

### ISSUE THREAD

**Issue by RachelLYY** [YuHengsss/YOLOV#17]
Hi! I notice that the input of this model is randomly selected from the original video. May I know how you make use of the non-keyframe information? And is the result of this model the full result of the video(including key and non-key frames) or just keyframe results? Thanks!

**Comment by YuHengsss** [comment]
Hello, all of the frames will act as key frames and they will refer to each other in our implementation and all frames in one batch will have prediction results.

**Comment by RachelLYY** [comment]
> Hello, all of the frames will act as key frames and they will refer to each other in our implementation and all frames in one batch will have prediction results.

Thanks! May I also ask another question: What's the 'Randomly select 𝑓 frames' mean in the model image in the paper?

**Comment by YilanWang** [comment]
> Randomly

It is the codes what you see in your question. The author random select f frames in the whole video, and use it to train and test

**Comment by YilanWang** [comment]
> > Hello, all of the frames will act as key frames and they will refer to each other in our implementation and all frames in one batch will have prediction results.
> 
> Thanks! May I also ask another question: What's the 'Randomly select 𝑓 frames' mean in the model image in the paper?

It is the codes what you see in your question. The author random select f frames in the whole video, and use it to train and test
