### ISSUE TITLE
How to start video training?

### ISSUE THREAD

**Issue by WangRuixin93** [YuHengsss/YOLOV#19]
I've seen the docs but didn't find guidance on how to start video training. Should I start with vid_train.py?
And if I have a trained detector, what should I do then to continue the video training part ?

**Comment by Yipzcc** [comment]
@WangRuixin93 Can you tell me how to start video training. Thank you!!!

**Comment by kangkang189** [comment]
hello,i meet some problems when i use"python tools/vid_train.py -f exps/yolov/yolov_x.py -c weights/yolov_x.pth -b 16 -d 2"to train the model ,i got wrong map ,do you know the correct command to get the correct map?thanks!

**Comment by Yipzcc** [comment]
@kangkang189 please use the weights of yolox_s.pth like
python tools/vid_train.py -f exps/yolov/yolov_x.py -c weights/yolox_s.pth -b 16 -d 2
