### ISSUE TITLE
Unable load .pth file 

### ISSUE THREAD

**Issue by Gaurav14cs17** [YuHengsss/YOLOV#2]
super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by YuHengsss** [comment]
> ```
> super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
> ```
> 
> RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

Could you please provide more details?
