### ISSUE TITLE
Is the best result from the first fine-turing epoch ? 

### ISSUE THREAD

**Issue by WangRuixin93** [YuHengsss/YOLOV#22]
Dear author, I've tried to train your yolov on my dataset and an obvious improvement was observed almost at the first epoch of fine-turing, but in later epoches, the performance never got better. If a big lr is used, the performace will get worse quickly from the first epoch. Did you meet similar situation during the fine-turing training on pretrained model ?

**Comment by YuHengsss** [comment]
For the VID and OVIS datasets, it will take about 3~4 epochs to get the best result, and then the performance decreases somewhat. You can try more augmentation in training, the code could be found in our x-large model pipeline.

**Comment by kangkang189** [comment]
> Dear author, I've tried to train your yolov on my dataset and an obvious improvement was observed almost at the first epoch of fine-turing, but in later epoches, the performance never got better. If a big lr is used, the performace will get worse quickly from the first epoch. Did you meet similar situation during the fine-turing training on pretrained model ?
你好，请问下你复现了作者YOLOV在VID数据集上的结果了吗，如果复现了能否+wechat像您咨询下如何正确的训练并得到85+MAP呢？谢谢！

**Comment by WangRuixin93** [comment]
我只在自己的数据上实验了&nbsp;


WRX
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月24日(星期六) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YuHengsss/YOLOV] Is the best result from the first fine-turing epoch ?  (Issue #22)





  
Dear author, I've tried to train your yolov on my dataset and an obvious improvement was observed almost at the first epoch of fine-turing, but in later epoches, the performance never got better. If a big lr is used, the performace will get worse quickly from the first epoch. Did you meet similar situation during the fine-turing training on pretrained model ?
 你好，请问下你复现了作者YOLOV在VID数据集上的结果了吗，如果复现了能否+wechat像您咨询下如何正确的训练并得到85+MAP呢？谢谢！

**Comment by asmallcat** [comment]
> 我只在自己的数据上实验了&nbsp; WRX ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月24日(星期六) 中午11:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [YuHengsss/YOLOV] Is the best result from the first fine-turing epoch ? (Issue #22) Dear author, I've tried to train your yolov on my dataset and an obvious improvement was observed almost at the first epoch of fine-turing, but in later epoches, the performance never got better. If a big lr is used, the performace will get worse quickly from the first epoch. Did you meet similar situation during the fine-turing training on pretrained model ? 你好，请问下你复现了作者YOLOV在VID数据集上的结果了吗，如果复现了能否+wechat像您咨询下如何正确的训练并得到85+MAP呢？谢谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，问一下在自己数据集上实验如何生成train_seq.npy和val_seq.npy，.npy里面存储的数据格式和内容是啥？谢谢

**Comment by WangRuixin93** [comment]
记不太清了，作者应该提供了样本，读取看一下内容，按照原格式生成自己的&nbsp;


WRX
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 中午1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YuHengsss/YOLOV] Is the best result from the first fine-turing epoch ?  (Issue #22)





  
我只在自己的数据上实验了&nbsp; WRX @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月24日(星期六) 中午11:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [YuHengsss/YOLOV] Is the best result from the first fine-turing epoch ? (Issue #22) Dear author, I've tried to train your yolov on my dataset and an obvious improvement was observed almost at the first epoch of fine-turing, but in later epoches, the performance never got better. If a big lr is used, the performace will get worse quickly from the first epoch. Did you meet similar situation during the fine-turing training on pretrained model ? 你好，请问下你复现了作者YOLOV在VID数据集上的结果了吗，如果复现了能否+wechat像您咨询下如何正确的训练并得到85+MAP呢？谢谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
您好，问一下在自己数据集上实验如何生成train_seq.npy和val_seq.npy，.npy里面存储的数据格式和内容是啥？谢谢
