### ISSUE TITLE
Unable to load pretrained checkpoints for yolov_x and yolov_l

### ISSUE THREAD

**Issue by vinceyoung** [YuHengsss/YOLOV#23]
Dear Author,

Thanks for sharing your great work. I'm trying to train yolov_l and yolov_x, but it looks like it's unable to load the checkpoints for `yoloxl_vid.pth` and `yoloxx_vid.pth` provided in google drive.

Here's my training command 
`python tools/vid_train.py -f exps/yolov/yolov_l.py -c pretrained_weights/yoloxl_vid.pth --fp16`
`python tools/vid_train.py -f exps/yolov/yolov_x.py -c pretrained_weights/yoloxx_vid.pth --fp16`

And I'm getting this error 

![image](https://user-images.githubusercontent.com/118837427/203380701-046256d7-8be4-46e8-8833-c4410397a4ba.png)

My command below for training yolov_s is working fine. Is it possible that the large and extra large checkpoints got corrupted?
`python tools/vid_train.py -f exps/yolov/yolov_s.py -c pretrained_weights/yoloxs_vid.pth --fp16`

Thanks for the help!

**Comment by YuHengsss** [comment]
> Dear Author,
> 
> Thanks for sharing your great work. I'm trying to train yolov_l and yolov_x, but it looks like it's unable to load the checkpoints for `yoloxl_vid.pth` and `yoloxx_vid.pth` provided in google drive.
> 
> Here's my training command `python tools/vid_train.py -f exps/yolov/yolov_l.py -c pretrained_weights/yoloxl_vid.pth --fp16` `python tools/vid_train.py -f exps/yolov/yolov_x.py -c pretrained_weights/yoloxx_vid.pth --fp16`
> 
> And I'm getting this error
> 
> ![image](https://user-images.githubusercontent.com/118837427/203380701-046256d7-8be4-46e8-8833-c4410397a4ba.png)
> 
> My command below for training yolov_s is working fine. Is it possible that the large and extra large checkpoints got corrupted? `python tools/vid_train.py -f exps/yolov/yolov_s.py -c pretrained_weights/yoloxs_vid.pth --fp16`
> 
> Thanks for the help!

Hello, thanks for your interest in our work. We find the same error with the two pretrain-weights and we have updated it, please try it again.

**Comment by vinceyoung** [comment]
It works for me now as well, thank you!
