### ISSUE TITLE
how to prepare the corresponding vid_train_coco.json file and train_seq.npy file

### ISSUE THREAD

**Issue by XiaoSue** [YuHengsss/YOLOV#26]
Hello, thank you very much for your excellent work. I want to know how to prepare the corresponding vid_train_coco.json file and train_seq.npy file if I want to use my own data set. Is there any guidance for training private data set on your project? thank you very much.

**Comment by YuHengsss** [comment]
Hello, thanks for your interest in our work. You can refer https://github.com/YuHengsss/YOLOV/issues/6#issuecomment-1236464310 which is the same question
