### ISSUE TITLE
Will the Argoverse dataset work?

### ISSUE THREAD

**Issue by YilanWang** [YuHengsss/YOLOV#27]
thx for the great work, and I found the Argoverse dataset has been implemented in vid.py. So I want to know does this dataset work? Or should I make some minor revisions on it? Many thx for your reply ~

**Comment by YuHengsss** [comment]
> thx for the great work, and I found the Argoverse dataset has been implemented in vid.py. So I want to know does this dataset work? Or should I make some minor revisions on it? Many thx for your reply ~

Hello, this dataset is used for additional experiments on Argoverse and OVIS which use coco-style annotation. You can find the annotation format at https://mtli.github.io/streaming/
