### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by hahapt** [YuHengsss/YOLOV#3]
When I try to run tools/train.py, I met a issue:

`/root/hhh/YOLO-master`
`unknown host, exit`

How can I figure out it?

**Comment by YuHengsss** [comment]
Thanks for your reminder, we have updated the training code. Please try it again.

**Comment by muzishen** [comment]
> Thanks for your reminder, we have updated the training code. Please try it again.

Hi, bro, i also met this bug.
Can you tell me what do you change this project?
