### ISSUE TITLE
Error(s) in loading state_dict for YOLOX:

### ISSUE THREAD

**Issue by aminprj** [YuHengsss/YOLOV#31]
Dear Author,

Thanks for sharing your work. I'm trying to run vid_demo.py and use  yoloxx_vid.pth and yoloxs_vid.pth, but it looks like it's unable to load the checkpoints for yoloxs_vid.pth and yoloxx_vid.pth provided in google drive. And I'm getting this error:
![issue01](https://user-images.githubusercontent.com/120318899/207116165-d89a8d58-b24c-42f6-80ea-30795bd0736f.PNG)

can you tell me what's wrong?

Thanks for the help!

**Comment by YuHengsss** [comment]
Hello, using demo for the video object detector, you should load weights from yolov rather than yolox.
