### ISSUE TITLE
 the use of the json file？

### ISSUE THREAD

**Issue by 294784045** [YuHengsss/YOLOV#32]
In "README", it is mentioned that the two files "YOLOV/annotations/vid_train_coco.json" and "YOLOv/yolox/data/dataset/train_seq.npy" are required, but I only see train_seq.npy is used in the project, json What and Where is the use of the json file? I‘m looking for reply，thanks

**Comment by shaotiancai** [comment]
> In "README", it is mentioned that the two files "YOLOV/annotations/vid_train_coco.json" and "YOLOv/yolox/data/dataset/train_seq.npy" are required, but I only see train_seq.npy is used in the project, json What and Where is the use of the json file? I‘m looking for reply，thanks

I have't seen the .json file used in the project, yet. Instead,  I set the annotation for per frame/photo in a .xml file (details at the def get_annotation(self,path,test_size) function in yolox/data/datasets/vid.py). All the .xml files can be stored in a Annotations directory. Now it works.

**Comment by shaotiancai** [comment]
> > In "README", it is mentioned that the two files "YOLOV/annotations/vid_train_coco.json" and "YOLOv/yolox/data/dataset/train_seq.npy" are required, but I only see train_seq.npy is used in the project, json What and Where is the use of the json file? I‘m looking for reply，thanks
> 
> I have't seen the .json file used in the project, yet. Instead, I set the annotation for per frame/photo in a .xml file (details at the def get_annotation(self,path,test_size) function in yolox/data/datasets/vid.py). All the .xml files can be stored in a Annotations directory. Now it works.

My wechat number is C894599326, welcome to talk together!

**Comment by Yipzcc** [comment]
[作者解答的问题](https://github.com/YuHengsss/YOLOV/issues/4#issuecomment-1227022382)，作者好像确实没用.json文件，为想问一下怎么训练自己的数据集，自己刚把数据集转换成VID格式了，但是不知道后续步骤咋操作，见reademe文件作者又用到了json文件

**Comment by 294784045** [comment]
> > > In "README", it is mentioned that the two files "YOLOV/annotations/vid_train_coco.json" and "YOLOv/yolox/data/dataset/train_seq.npy" are required, but I only see train_seq.npy is used in the project, json What and Where is the use of the json file? I‘m looking for reply，thanks
> > 
> > 
> > I have't seen the .json file used in the project, yet. Instead, I set the annotation for per frame/photo in a .xml file (details at the def get_annotation(self,path,test_size) function in yolox/data/datasets/vid.py). All the .xml files can be stored in a Annotations directory. Now it works.
> 
> My wechat number is C894599326, welcome to talk together!

Thanks for your reply !!!

**Comment by qin-yuhao** [comment]
> 具体可以见[作者解答的问题](https://github.com/YuHengsss/YOLOV/issues/4#issuecomment-1227022382)，作者确实没用.json文件。想问一下怎么训练自己的数据集，自己刚把数据集转换成VID格式了，但是不知道后续步骤怎么操作，见reademe文件作者又用到了json文件

搞不懂他在搞什么，代码里是xml，他却一直说用到了json

**Comment by qin-yuhao** [comment]
> > 具体可以见[作者解答的问题](https://github.com/YuHengsss/YOLOV/issues/4#issuecomment-1227022382)，作者确实没用.json文件。想问一下怎么训练自己的数据集，自己刚把数据集转换成VID格式了，但是不知道后续步骤怎么操作，见reademe文件作者又用到了json文件
> 
> 搞不懂他在搞什么，代码里是xml，他却一直说用到了json

怎么做数据集readme也不说清楚

**Comment by Yipzcc** [comment]
你需要变训练yolox后再训练yoloV
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年06月19日 03:23 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [YuHengsss/YOLOV] the use of the json file？ (Issue #32) 
具体可以见作者解答的问题，作者确实没用.json文件。想问一下怎么训练自己的数据集，自己刚把数据集转换成VID格式了，但是不知道后续步骤怎么操作，见reademe文件作者又用到了json文件
搞不懂他在搞什么，代码里是xml，他却一直说用到了json
怎么做数据集readme也不说清楚
