### ISSUE TITLE
OVIS数据集如何评估？

### ISSUE THREAD

**Issue by asmallcat** [YuHengsss/YOLOV#39]
您好，非常感谢您的工作！我有一些问题，我没找到评估OVIS数据集的方法，vid_eval.py 评估的加载的VID_dataset数据集的验证集。OVIS数据集如何评估？我是在自定义的数据集上实验是COCO格式标注，没办法评估模型的好坏？谢谢！

**Comment by YuHengsss** [comment]
Hello, we don't have annotation for OVIS val set and we obtain the results for OVIS by uploading the detection result to their evaluation server. You can convert the raw prediction to coco format. Please refer to https://github.com/YuHengsss/YOLOV/issues/10#issuecomment-1240119172 for more details.

**Comment by asmallcat** [comment]
感谢您的回复！再问一下您那如何得到YOLOV的检测结果呢？我已经将自定义数据集转成COCO格式，在自定义的数据集情况下，如何设置YOLOV的验证集呢？谢谢
