### ISSUE TITLE
Multi gpu stuck after the first epoch when training yolox

### ISSUE THREAD

**Issue by shaotiancai** [YuHengsss/YOLOV#40]
I see the paper where 2/4 gpus can directly used to train the yolox model. However, I suffer from the stuck problem of multi gpu when training yolox model. Does anyone know how to solve this problem? Thank you!

**Comment by shaotiancai** [comment]
> 

@YuHengsss

**Comment by shaotiancai** [comment]
According to the install step provided in readme.md, the problem solve.

**Comment by hutIngk** [comment]
I also encountered this problem. When I use multiple GPUs for training, I get stuck.Have you solved it?
