### ISSUE TITLE
AttributeError: 'MosaicDetection_VID' object has no attribute 'dataset_pth'

### ISSUE THREAD

**Issue by HwaiHo-0552** [YuHengsss/YOLOV#41]
!! Iteration after 3 epoch. !! Running for yolov_x stopped. !!

But, following the bottom structure could smoothly running for yolov_s. 
pytorch 1.20, cuda 11.6.

The 'AttributeError' seems to related the path of dataset ? I am not sure.
But, running for yolov_s is OK.
Does anyone here could give a help ? Thank you so much.

**Comment by HwaiHo-0552** [comment]
YOLOV -> annotations
             -> assets
             -> .......... 
             -> exps
             -> ILSVRC -> Annotations
                               -> Data
                               -> ImageSets
             -> ILSVRC2015 -> Annotations
                                      -> Data
                                      -> ImageSets
             -> yolox
             -> ........

**Comment by HwaiHo-0552** [comment]
I checked ./exps/yolov_x.py

I saw these code.         
dataset = vid.VIDDataset(file_path='./yolox/data/datasets/train_seq.npy',
                                              img_size=self.input_size,
                                              preproc=TrainTransform(
                                              max_labels=50,
                                              flip_prob=self.flip_prob,
                                              hsv_prob=self.hsv_prob),
                                              lframe=0,  # batch_size,
                                              gframe=batch_size,
                                             dataset_pth=self.data_dir)

For the "train_seq.npy", I had put it as author's guide before running.

**Comment by HwaiHo-0552** [comment]
I solved this issue.
line 281 self.dataset_path = dataset_path in mosaicidetection.py.

if you want to train yolov_x.py,
please modify this line as  **self.dataset_path** = dataset_path -->  **self.dataset_pth** = dataset_path.

OK!!    checking code carefully!

**Comment by YuHengsss** [comment]
> I solved this issue. line 281 self.dataset_path = dataset_path in mosaicdetection.py.
> 
> if you want to train yolov_x.py, please modify this line as **self.dataset_path** = dataset_path --> **self.dataset_pth** = dataset_path.
> 
> OK!! checking code carefully!

Sorry for my poor code and thanks for your debugging. Best wishes.
