### ISSUE TITLE
why use only part of the data?

### ISSUE THREAD

**Issue by xiaowk5516** [YuHengsss/YOLOV#42]
Hello, thx for your great work. I notice that you use only part of the data in dataloader.
![image](https://user-images.githubusercontent.com/59595896/218311531-f41582ed-53d3-4a8e-acdd-127c5b10f59c.png)

does this mean “use 10% of VID”？short-time video may not appear in the dataset.

**Comment by YuHengsss** [comment]
Hello, "10% of VID datasets" is the setting to train the base detector. The "15000" is the sequence number for training the video object detector, which is about 1/4 data of the whole dataset.

**Comment by YuHengsss** [comment]
May boost the accuracy a little, taking all data for training costs soooo much time for the VID Dataset.

**Comment by xiaowk5516** [comment]
> Hello, "10% of VID datasets" is the setting to train the base detector. The "15000" is the sequence number for training the video object detector, which is about 1/4 data of the whole dataset.

thx for reply. 

do you train the base detector using 10% of VID and DET detaset or only 10% of DET dataset?
The "tnum" means using part of val dataset to calculate the performance of model.  is that right?

**Comment by xiaowk5516** [comment]
> May boost the accuracy a little, taking all data for training costs soooo much time for the VID Dataset.

Got it. I have tried using all data training yolov6. 4 hours per epoch. hahhaha

**Comment by YuHengsss** [comment]
> > Hello, "10% of VID datasets" is the setting to train the base detector. The "15000" is the sequence number for training the video object detector, which is about 1/4 data of the whole dataset.
> 
> thx for reply.
> 
> do you train the base detector using 10% of VID and DET detaset or only 10% of DET dataset? The "tnum" means using part of val dataset to calculate the performance of model. is that right?

Yes. 10% VID data. The video part is redundant.

**Comment by xiaowk5516** [comment]
> > > Hello, "10% of VID datasets" is the setting to train the base detector. The "15000" is the sequence number for training the video object detector, which is about 1/4 data of the whole dataset.
> > 
> > 
> > thx for reply.
> > do you train the base detector using 10% of VID and DET detaset or only 10% of DET dataset? The "tnum" means using part of val dataset to calculate the performance of model. is that right?
> 
> Yes. 10% VID data. The video part is redundant.

thanks a lot
