### ISSUE TITLE
Do I need to train yolox and then train yolov when I train my data set? I don't see a correlation between the two models.

### ISSUE THREAD

**Issue by tgf123** [YuHengsss/YOLOV#43]
Do I need to train yolox and then train yolov when I train my data set? I don't see a correlation between the two models.

**Comment by YuHengsss** [comment]
> Do I need to train yolox and then train yolov when I train my data set? I don't see a correlation between the two models.

Hello, yolov should take the pretrain weights of yolox for we do not BP paramaters in yolox model. You can find more details in our paper.

**Comment by tgf123** [comment]
> 
That is, when I train my data set, I need to train yolox first, and then train yolox trained weights in yolov

**Comment by YuHengsss** [comment]
yep

**Comment by tgf123** [comment]
> 是的

I have noted. Thank you very much for your reply

**Comment by tgf123** [comment]
> 

Could you be a little more specific?

**Comment by tgf123** [comment]
about not BP paramaters in yolox model

**Comment by tgf123** [comment]
Do you mean there are no BP paramaters in the yolox section of the yolov model？

**Comment by YuHengsss** [comment]
Check the code bro

**Comment by tgf123** [comment]
> Check the code bro
Ok, I'll take a closer look. Thank you for your reply
