### ISSUE TITLE
imagenet_vid_groundtruth_motion_iou.mat

### ISSUE THREAD

**Issue by heartworm1** [YuHengsss/YOLOV#45]
Hello, I'm confused about what is  the content of the file"imagenet_vid_groundtruth_motion_iou.mat"?
and how to make it?

**Comment by YuHengsss** [comment]
hi there, I think you could find helpful information for  the REEP repo

**Comment by heartworm1** [comment]
> hi there, I think you could find helpful information for the REPP repo :https://github.com/AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection

so this file is generated by the repp model and then you copy it  to the yolov model?

**Comment by YuHengsss** [comment]
Yep,we adopt REPP for post-processing.

**Comment by heartworm1** [comment]
Ok, thank you very much.
