### ISSUE TITLE
YOLOX outperforms YOLOV on different dataset using "vid" optimization settings

### ISSUE THREAD

**Issue by akanuasiegbu** [YuHengsss/YOLOV#52]
Hi, do you have any tips on how to improve YOLOV performance? I'm training YOLOV on a different dataset and numerically found that YOLOX produced better results. Maybe it's hyperparameter tuning specific to the dataset? To be clear I trained YOLOX on this particular dataset using the hyperparameter settings in "yoloxs_vid.py". Then used the trained YOLOX model to initialize the YOLOV backbone and trained YOLOV using the hyperparameter setting in "yolovs_vid.py". Note that I am using only local frames and I am not using any global frames.

**Comment by YuHengsss** [comment]
Hi there, you could expand the stride (defualt=1) of sampling local frames which could boost detection accuracy.

**Comment by YangBo0411** [comment]
> Hi, do you have any tips on how to improve YOLOV performance? I'm training YOLOV on a different dataset and numerically found that YOLOX produced better results. Maybe it's hyperparameter tuning specific to the dataset? To be clear I trained YOLOX on this particular dataset using the hyperparameter settings in "yoloxs_vid.py". Then used the trained YOLOX model to initialize the YOLOV backbone and trained YOLOV using the hyperparameter setting in "yolovs_vid.py". Note that I am using only local frames and I am not using any global frames.

Have you solved this problem? I am currently facing the same problem, YOLOX performs better than YOLOV. How did you adjust the parameters?
