### ISSUE TITLE
训练自己的数据集--样本标定问题

### ISSUE THREAD

**Issue by jijiangyan** [YuHengsss/YOLOV#54]
您好，请教您个问题，希望您有空帮忙解答一下，提前感谢！
之前没有接触过视频目标检测，有个问题比较疑惑，请问训练YOLOV模型时，针对视频中的每帧图像样本，除了标定目标的位置，是否需要将视频中的各目标ID也要一起标定？如果仅仅做静态图像的目标检测时（YOLOX），训练自己的数据集是不需要标定ID信息的。
期待您的回复！

**Comment by YuHengsss** [comment]
关于 video object detection 任务描述可以参考：https://image-net.org/challenges/LSVRC/2015/index#maincomp
