### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by lsl0901** [YuHengsss/YOLOV#57]
作者您好！！十分感激您的工作和努力！！
我想训练自己的数据集，我该如何安排和重构我的数据集呢，或者说我需要生成哪些文件，他们的构成又是什么样的。
再次感谢！！

**Comment by YuHengsss** [comment]
您好，关于视频数据的标注可以参考 OVIS 数据集的格式（只标注box）或者 Argoverse 的格式。我们代码里提供了将它们转化为coco标注格式以及数据加载的pipline：
https://github.com/YuHengsss/YOLOV/blob/8fe37e4bcd64ff9b50cbd5a97775a754cb041510/yolox/data/datasets/vid.py#L204
https://github.com/YuHengsss/YOLOV/blob/8fe37e4bcd64ff9b50cbd5a97775a754cb041510/yolox/data/datasets/vid.py#L414
https://github.com/YuHengsss/YOLOV/blob/8fe37e4bcd64ff9b50cbd5a97775a754cb041510/yolox/data/datasets/ovis.py#L238

**Comment by lsl0901** [comment]
@YuHengsss 
感谢您的回复！我会尝试您的建议。

**Comment by YangBo0411** [comment]
> @YuHengsss 感谢您的回复！我会尝试您的建议。

你好，你成功了吗？我卡在准备数据集这了
