### ISSUE TITLE
Error using vid_demo.py

### ISSUE THREAD

**Issue by medinaltbx** [YuHengsss/YOLOV#58]
First of all, thanks for your work, it's really useful. 

I'm facing an error using the vid_demo.py for video inference using YOLOV\exps\yolov\yolov_s.py and YOLOV\weights\yolov_s.pth. The error I'm getting is ZeroDivisionError: float division by zero when trying to test the inference on a custom video. I provide a screenshot of the error below:

![image](https://github.com/YuHengsss/YOLOV/assets/54904725/42f41d80-958e-498d-8428-3b136eafea80)

I just followed the instalation steps as referred on the README.md file, using a conda environment. I'm running it on Windows 11.

**Comment by YuHengsss** [comment]
Please check the --path parameter, it seems opencv doesn't get the video

**Comment by medinaltbx** [comment]
Thanks for answering so quickly.

It seems that is something going on with the video. Before running vid_demo.py, my target video looks normal:

![image](https://github.com/YuHengsss/YOLOV/assets/54904725/e0da63a5-54ce-4ee6-94d9-6295c3a97c2f)

However, after running the script the video seems corrupt somehow:

![image](https://github.com/YuHengsss/YOLOV/assets/54904725/ea18f5d4-08fc-47ef-b332-5d908e7a8618)

![image](https://github.com/YuHengsss/YOLOV/assets/54904725/0de60ba0-51e8-4618-b016-8cd85ec5b9bf)

After this, the video is no longer readable

**Comment by medinaltbx** [comment]
The error occured because the video file was corrupted.

**Comment by andynnnnn** [comment]
> 发生此错误是因为视频文件已损坏。

嘿，朋友你好，我也出现了类似问题，进行vid_demo测试的时候，传入视频运行vid_demo失败后发现已损坏，请问你是如何解决的呢？谢谢
