### ISSUE TITLE
Input type and weight type mismatch

### ISSUE THREAD

**Issue by medinaltbx** [YuHengsss/YOLOV#59]
Hello, while trying to execute vid_demo.py on CPU to test the yolov_s.pth model with an MP4 video (416px), I encountered the following error:

![image](https://github.com/YuHengsss/YOLOV/assets/54904725/aa8454a7-78d3-499a-85f9-7d3bcd5b40f1)

I haven't modified the code in vid_demo.py or yolov_s.py. Command used:

python tools\vid_demo.py -f exps\yolov\yolov_s.py -c weights\yolov_s.pth --path videos\test_17.mp4 --conf 0.25 --nms 0.5 --tsize 576 --device cpu

Thank you for your work.

**Comment by Rownak** [comment]
Hi @medinaltbx have you got any solution to this error? I have been getting the same error. 
"RuntimeError: Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor"
![yolov_error](https://github.com/YuHengsss/YOLOV/assets/7727454/24ce0931-a660-4d08-829e-48896617ef13)
