### ISSUE TITLE
如果换成自定义数据的类别，需要重新训练yolov还是单独的yolox

### ISSUE THREAD

**Issue by le02146** [YuHengsss/YOLOV#63]
请问如果我现在在自定义的数据集上需要检测某个新类别（不在coco80类）， 已经训练好YOLOX了。请问如果在一个视频上进行检测，可以直接用yolov的权重吗，还是需要重新训练yolov ？ 谢谢

**Comment by YuHengsss** [comment]
需要使用 yolox 的权重初始化 yolov 进行训练

**Comment by le02146** [comment]
您好，谢谢回复。  我只是在图片上训练一个新的类别A（不在`COCO_CLASSES`，也不在`VID_classes`）的`图片`yolox检测器，然后用到了视频上检测A。   因为视频出现漏检（有的帧没有检测到）所以想利用yolov 来提高。
 请问您的意思我还不能直接结合我自己训练的yolox 和yolov的方法吗 ?需要我自己标注视频目标的数据来重新训练/微调yolov才能用吗
谢谢

**Comment by YuHengsss** [comment]
是的，因为yolov的分类器与yolox是分离的，需要在yolox的基础上进行finetuning

**Comment by le02146** [comment]
这样的话，就比较麻烦了。现在只是用图片的标注数据来训练，没有时间和成本去专门再标注类别A的视频检测数据集。 
能不能请教您一下，有没有其他方法可以直接利用图片检测器来提高视频检测效果的，比如跟踪方法可以吗，谢谢您。

**Comment by YuHengsss** [comment]
可以尝试一些后处理的方法，比如：https://github.com/AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection
这种方法不需要训练，能出框的检测器都可以直接拿过来用

**Comment by le02146** [comment]
谢谢

**Comment by njit0217** [comment]
> 可以尝试一些后处理的方法，比如：https://github.com/AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection 这种方法不需要训练，能出框的检测器都可以直接拿过来用

请问一下，当用自己的数据，repp需要微调一下吗？还是说直接使用它的模型
