### ISSUE TITLE
How to manage YOLOXX_ Vid.pth for pre training

### ISSUE THREAD

**Issue by chenhao324** [YuHengsss/YOLOV#65]
May I ask how to train yoloxx_vid.pth before adding video classification branch fine-tuning？ Which .py file was used for the pre training model of yoloxx_vid.pth？

**Comment by YuHengsss** [comment]
Refer to https://github.com/YuHengsss/YOLOV/blob/28ff8b097d158a9f86e616cd88eed21e4e4fa7e9/exps/yolov/yoloxx_vid.py#L6, note that you should use train.py instead of vid_train.py for training the still image detector.
