### ISSUE TITLE
A question about the resize operation

### ISSUE THREAD

**Issue by XingtongGe** [YuHengsss/YOLOV#68]
Hi, great work! 

In your paper, the test image size used is 576*576, while the image size used by most VOD methods is about 600*1000, which is larger than what you used. Have you tried using the latter image size? Would this help enhance detection performance? Thanks!

**Comment by YuHengsss** [comment]
Thanks.

We have tried larger image size and selected 576 * 576 as the optimal setting for our detector. The performance drop even when we take the image size as 640 * 640.  We hypothesize that the primary cause of this performance degradation is the low resolution of the ImageNet VID dataset. We would appreciate any further insights or suggestions you might have on this matter.

**Comment by XingtongGe** [comment]
Got it, thanks for your reply!
