### ISSUE TITLE
Issues related to vid_train.py

### ISSUE THREAD

**Issue by RookieHuang** [YuHengsss/YOLOV#70]
I try to run vid_train.py,but I found it seems like a evaluation script with "dataset_val" and "val_loader".How can I finetune a VID object detector with "vid_train_coco.json"?The VIDDataset class in vid.py only support xml format.
LOOKING FORWARD TO YOUR REPLY!

**Comment by YuHengsss** [comment]
You should not finetune the VID object detector via "vid_train_coco.json", the annotation file for finetuning video object detector is defined here: https://github.com/YuHengsss/YOLOV/blob/28ff8b097d158a9f86e616cd88eed21e4e4fa7e9/exps/yolov/yolov_base.py#L71

try following steps to download the annotation file:

Download our COCO-style annotations for [training](https://drive.google.com/file/d/1HhE4OAcc--CpjUj69JCRXzMvIRsR4ymM/view?usp=sharing) and [video sequences](https://drive.google.com/file/d/1vJs8rLl_2oZOWCMJtk3a9ZJmdNn8cu-G/view?usp=sharing). Then, put them in these two directories:

YOLOV/annotations/vid_train_coco.json
YOLOV/yolox/data/dataset/train_seq.npy
Change the data_dir in exp files to [path to your datasets] and Download our weights.
