### ISSUE TITLE
Unable to eval

### ISSUE THREAD

**Issue by linansheng** [YuHengsss/YOLOV#8]
[train_log .txt](https://github.com/YuHengsss/YOLOV/files/9487961/train_log.txt)
can you tell me how to deal with it when evaluate

**Comment by YuHengsss** [comment]
> [train_log .txt](https://github.com/YuHengsss/YOLOV/files/9487961/train_log.txt) can you tell me how to deal with it when evaluate

The vid_eval.py file only support rough offline evalutaion. For online evaluation, the code is being sorted, please wait for a moment.

**Comment by linansheng** [comment]
thank you！！
