### ISSUE TITLE
大佬，训练的模型可以给一个百度网盘的链接么？

### ISSUE THREAD

**Issue by CangHaiQingYue** [YuHengsss/YOLOV#85]
如题，你懂得~
感谢！

**Comment by YuHengsss** [comment]
Which one?

**Comment by CangHaiQingYue** [comment]
> Which one?

yolov-s and yolov-l
yolov++-s and yolov++l

**Comment by AngstCJ** [comment]
> @YuHengsss thanks!
> 
> > Which one?
> 
> yolov-s and yolov-l yolov++-s and yolov++l And the corresponding YOLOX model...

These are the weights you need. 链接: https://pan.baidu.com/s/1UDMQeJvNXvyzTHP7Mm1zjw?pwd=6hfs 提取码: 6hfs 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by CangHaiQingYue** [comment]
> > @YuHengsss thanks!
> > > Which one?
> > 
> > 
> > yolov-s and yolov-l yolov++-s and yolov++l And the corresponding YOLOX model...
> 
> These are the weights you need. https://pan.baidu.com/s/1UDMQeJvNXvyzTHP7Mm1zjw?pwd=6hfs

thank you very much!
